### IMPORTING LIBRARIES

In [64]:
import pandas as pd
import numpy as np

### IMPORTING THE DATASET

In [65]:
audible_dataset=pd.read_csv(r'DATASETS\audible_uncleaned.csv')

## SUMMARY OF THE DATA
### THIS CONTAINS IMPORTANT DATA OF AUDIOBOOKS RELEASED FROM 1998 TO 2025
IT CONTAINS 87489 ROWS AND 8 COLUMNS

## COLUMN DETAILS
### It contains 9 columns
- **NAME**: Name of audiobook
- **AUTHOR**: Author of the audiobook
- **NARRATOR**: Narrator of the audiobook
- **TIME**: Length of the audiobook
- **RELEASEDATE**: Release date of the audiobook
- **LANGUAGE**: Language of the audiobook
- **STARS**: Number of stars the audiobook received
- **PRICE**: Price of the audiobook in INR
- **RATINGS**: Number of reviews received by the audiobook

# Issues Identified During Manual Inspection

## Dirty Data Issues

1. Column names are not standardized and need to be corrected.

2. The `Name` column contains:
   - Spelling mistakes
   - Character encoding issues (e.g., `â€™`, `Ã©`, `Ð`, `Ñ`)

3. Remove the prefix `WrittenBy:` from the `Written By` column.

4. Author names should be separated into:
   - First Name
   - Last Name

5. The `Written By` column contains encoding issues.

6. Remove the prefix `NarratedBy:` from the `Narrator` column.

7. The `Narrator` column contains encoding issues.

8. Narrator names should be separated into:
   - First Name
   - Last Name

9. The `Time` column should be converted to an appropriate datetime/time format.

10. Many records contain `Anonymous` as the author or narrator also some contain uncredited replace them with unknown

11. The `Release Date` column should be converted to datetime format.
    - Mixed date formats are present:
      - `DD-MM-YYYY`
      - `MM-DD-YYYY`

12. The `Language` column contains inconsistent capitalization:
    - Uppercase values
    - Lowercase values
    - Title Case values

13. The `Price` column should be converted to a numeric data type also some entries are free which we need to change to 0

14. The `Rating` column contains some empty values which are represented as 'Not rated yet"

## UPON AUTOMATIC ASSESSMENT FOLLOWING ISSUES WERE FOUND
1. Some entries in author do not end with an alphabet.
2. Some entries in narrator do not end with an alphabet.
3. Some duration entries contain "Less than 1 min".
4. Some author entries contain role keywords such as editor, illustrator, traductor, translator, etc.

---

## Untidy Data Issues

1. The `Ratings` column contains multiple variables in a single column:
   - Star Rating
   - Number of Reviews

   These should be separated into two independent columns:

   - `Stars`
   - `Number_of_Reviews`

In [66]:
audible_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 87489 entries, 0 to 87488
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         87489 non-null  str
 1   author       87489 non-null  str
 2   narrator     87489 non-null  str
 3   time         87489 non-null  str
 4   releasedate  87489 non-null  str
 5   language     87489 non-null  str
 6   stars        87489 non-null  str
 7   price        87489 non-null  str
dtypes: str(8)
memory usage: 5.3 MB

In [67]:
audible_dataset.sample(10)

,name,author,narrator,time,releasedate,language,stars,price
2051,Toucans,"Writtenby:MaryR.Dunn,AnneHobbs",Narratedby:anonymous,2 mins,02-03-22,English,Not rated yet,82.00
84796,Majesty,Writtenby:KatharineMcGee,Narratedby:BrittanyPressley,12 hrs and 39 mins,03-09-20,English,4 out of 5 stars4 ratings,615.00
66608,De Todo Coração,Writtenby:LucianoSubirá,Narratedby:Fábio,7 hrs and 36 mins,06-10-21,portuguese,Not rated yet,166.00
78707,Wyoming Winter,Writtenby:DianaPalmer,Narratedby:ToddMcLaren,10 hrs and 45 mins,31-10-17,English,Not rated yet,"1,005.00"
29981,2h chrono pour mieux s'organiser,Writtenby:JulienGueniat,Narratedby:PatrickKuban,4 hrs and 34 mins,25-08-21,french,Not rated yet,660.00
32741,Program Your Dreams,Writtenby:DickSutphen,Narratedby:DickSutphen,51 mins,15-12-21,English,Not rated yet,258.00
7177,Christmas Trees,Writtenby:RobertFrost,Narratedby:GlennHascall,2 mins,05-12-14,English,Not rated yet,239.00
70267,Mr. Gandys große Reise,Writtenby:AlanTitchmarsh,Narratedby:BodoWolf,9 hrs and 35 mins,09-10-17,german,Not rated yet,367.00
85539,Spider-Man: Carnage in New York,"Writtenby:DavidMichelinie,DeanWesleySmith,Marvel",Narratedby:TimPaige,3 hrs and 51 mins,01-10-19,English,4 out of 5 stars1 rating,703.00
56189,Rede de Mentiras [Network of Lies],Writtenby:JasSilva,"Narratedby:MarcoNepomuceno,AnnaKorby",10 hrs and 13 mins,09-01-20,portuguese,Not rated yet,836.00

In [68]:
audible_dataset.duplicated().sum()

np.int64(0)

In [69]:
audible_dataset.describe()

,name,author,narrator,time,releasedate,language,stars,price
count,87489,87489,87489,87489,87489,87489,87489,87489
unique,82767,48374,29717,2284,5058,36,665,1011
top,The Art of War,"Writtenby:矢島雅弘,石橋遊",Narratedby:anonymous,2 mins,16-05-18,English,Not rated yet,586.00
freq,20,874,1034,372,773,61884,72417,5533

In [70]:
audible_dataset.head()

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
1,The Burning Maze,Writtenby:RickRiordan,Narratedby:RobbieDaymond,13 hrs and 8 mins,01-05-18,English,4.5 out of 5 stars41 ratings,820.00
2,The Deep End,Writtenby:JeffKinney,Narratedby:DanRussell,2 hrs and 3 mins,06-11-20,English,4.5 out of 5 stars38 ratings,410.00
3,Daughter of the Deep,Writtenby:RickRiordan,Narratedby:SoneelaNankani,11 hrs and 16 mins,05-10-21,English,4.5 out of 5 stars12 ratings,615.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00

In [71]:
audible_dataset.tail()

,name,author,narrator,time,releasedate,language,stars,price
87484,Last Days of the Bus Club,Writtenby:ChrisStewart,Narratedby:ChrisStewart,7 hrs and 34 mins,09-03-17,English,Not rated yet,596.00
87485,The Alps,Writtenby:StephenO'Shea,Narratedby:RobertFass,10 hrs and 7 mins,21-02-17,English,Not rated yet,820.00
87486,The Innocents Abroad,Writtenby:MarkTwain,Narratedby:FloGibson,19 hrs and 4 mins,30-12-16,English,Not rated yet,938.00
87487,A Sentimental Journey,Writtenby:LaurenceSterne,Narratedby:AntonLesser,4 hrs and 8 mins,23-02-11,English,Not rated yet,680.00
87488,Havana,Writtenby:MarkKurlansky,Narratedby:FleetCooper,6 hrs and 1 min,07-03-17,English,Not rated yet,569.00

In [72]:
audible_dataset['name'].tolist()

['Geronimo Stilton #11 & #12',
 'The Burning Maze',
 'The Deep End',
 'Daughter of the Deep',
 'The Lightning Thief: Percy Jackson, Book 1',
 'The Hunger Games: Special Edition',
 'Quest for the Diamond Sword',
 'The Dark Prophecy',
 'Merlin Mission Collection',
 'The Tyrant’s Tomb',
 "The Titan's Curse: Percy Jackson, Book 3",
 'Magic Tree House Collection: Books 9-16',
 'Magic Tree House Collection: Books 1-8',
 'Magnus Chase and the Ship of the Dead',
 'Northern Lights',
 'Geronimo Stilton #13 and #14',
 'Magic Tree House Collection',
 'Exile',
 'Merlin Mission Collection',
 'Neverseen',
 'The Tower of Nero',
 'Eldest: The Inheritance Cycle, Book 2',
 'Artemis Fowl',
 'Geronimo Stilton 22 & 24',
 'Percy Jackson and the Battle of the Labyrinth',
 'Winnie-the-Pooh',
 'Magic Tree House Collection: Books 25-32',
 'Geronimo Stilton #20 and #21',
 'The Red Pyramid',
 "Mystery of the Griefer's Mark",
 'Geronimo Stilton #17',
 'The House at Pooh Corner',
 'Mission Unstoppable',
 'Darkness of Dragons',
 '14 Short Stories Bundle for Kids: Adventure, Science Fiction, Aesop’s Fables, Classic Fairy Tales and Christmas Story Books for Children',
 'The Adventures of Rusty',
 'Geronimo Stilton #15 and #16',
 'The Lost Heir',
 'Everblaze',
 'Treasure Hunters in Trouble',
 'Lodestar',
 'Curse of the Arctic Star',
 'The Ghost of Grey Fox Inn',
 "Rowley Jefferson's Awesome Friendly Adventure",
 'Flashback',
 'Secret of the Red Arrow',
 'The Lightning Thief: Percy Jackson, Book 1',
 'Clash of the Creepers',
 'The Skeletons Strike Back',
 'Dragonslayer',
 'A Bear Called Paddington',
 'Gregor and the Curse of the Warmbloods',
 'The Dark Secret',
 "The Gruffalo's Child",
 'Merlin Mission Collection',
 'Keys to the Demon Prison',
 'Legacy',
 'The Endermen Invasion',
 'Captain Underpants and the Revolting Revenge of the Radioactive Robo-Boxers',
 'You Only Die Twice',
 'From Texas with Love',
 'Across the Desert',
 'Unicorn Academy: Aisha and Silver',
 'Laura Blackman and The Five Cunning Aardvarks',
 'The Dragonet Prophecy',
 'Dangerous Gift',
 'The 39 Clues, Book 6',
 'Never Say Genius',
 'The Madman of Black Bear Mountain',
 'Unicorn Academy: Zara and Moonbeam',
 'El fantasma de la bodega',
 'El paseo encantado',
 'Wigetta',
 'Aru Shah and the Nectar of Immortality',
 'Barnabas der Wolkenschaufler',
 'The Boy in the Post',
 'Thornwood',
 "7 histoires d'aventures !",
 'Le Loup qui devenait chef de la forêt',
 'Curse of the Robo-Dragon',
 'Call of the Crow',
 'Glass Slippers',
 'Captain Underpants and the Sensational Saga of Sir Stinks-a-Lot',
 'Tiger Honor',
 'The Amulet of Samarkand',
 "Rowley Jefferson's Awesome Friendly Spooky Stories",
 'Lost in the End',
 'Trouble Island',
 'Terrors of the Forest',
 'Riverboat Roulette',
 'The Book of Chaos',
 'Fortunately, the Milk...',
 'Discoveries in the Overworld',
 'The Last Human',
 'Welcome to Smellville',
 "An Explorer's Guide to the Nether",
 'The Midnight Gang',
 'As the Falcon Flies',
 'The Squad of Lucky Landing: An Unofficial Fortnite Adventure Novel',
 'Pahua and the Soul Stealer',
 'El monstruo marino secreto',
 'Sabotage on the Solar Express',
 'A Boy Called Christmas',
 'The 39 Clues, Book 4',
 'The 39 Clues, Book 3',
 'The Disappearance',
 'Once Upon a Crime',
 'Billionaire Boy',
 'The Blue Lady of Coffin Hall',
 "Danger at Dead Man's Pass",
 'Unlocked',
 'The Danger Gang',
 'Mountain Mare',
 'The Princess in Black and the Mermaid Princess',
 'The Vanishing Statue',
 'Eye of the Earthquake Dragon',
 'Peril at Granite Peak',
 'Barbie - Aventura espacial',
 'The Disappearance of Emily Downs',
 'The Solution',
 'The Great Greenfield Bake-Off',
 'Into Thin Air',
 'Once upon a Thriller',
 "The Magician's Nephew",
 'Leonora Bolt: Secret Inventor',
 'The Snail and the Whale',
 'Tigers for Dinner',
 'The Hidden Kingdom',
 'Eagle Strike',
 'Captain Marvel - Ultron blir viral',
 'Toy Story 4',
 'Three Lost Seeds',
 'Mystery on the Mayhem Express',
 'Tunnel of Secrets',
 'Barbie - La puerta secreta',
 'A scuola con Pongo e Tim: Henry Every',
 'Black Panther: Spellbound',
 'The 39 Clues: Unstoppable, Book 3',
 'Hello Kitty - El Club de la Amistad',
 'Treasure Island',
 'The Human Body',
 'Minecraft: The Dragon',
 'The Christmasaurus and the Naughty List',
 'Das Exil',
 'El Cerdito de Navidad [The Christmas Pig]',
 'Big Change for Stuart',
 'The Imagination Box: Beyond Infinity',
 'Camp Daze',
 'Vaiana',
 'Myth of the Rain Forest Monster',
 'Little Badman and the Time-travelling Teacher of Doom',
 'The Great Dream Robbery',
 'Barbie - Superprincesa',
 'Barbie - El campamento de princesas',
 'Barbie - Dreamtopia',
 'Barbie - Superprincesa',
 'Among Us Book - Red Diary',
 'We’re Going to Find the Monster',
 'Ut i det vilda',
 'The Imagination Box: A Mind of Its Own',
 "Dungeons & Dragons: The Mad Mage's Academy",
 'Scary Stories for Young Foxes: The City',
 'Med kunglig stämpel',
 'Bolt',
 'The Tenth Son',
 'Escape from Falaise',
 'The Jungle Book',
 'PJ Masks - 3-Minuten-Gutenachtgeschichten',
 'Opapi-Opapa - Volle Kraft voraus!',
 'Opapi-Opapa - Besuch von den Krawaffels',
 'Als Papa auf einen Knopf drückte und wir fast von einem Dino gefressen wurden',
 'Spidey og hans fantastiske venner',
 'Phantom Stallion: Blue Wings',
 'Super Pigiamini - Storie della buonanotte da 5 minuti',
 'Lost Island',
 'The Boy Who Hatched Monsters',
 'The Magic Ocean Slide & The Giant Conker',
 'Krieg der Fluten',
 'The Secret of Splint Hall',
 'Tschakka! - Freunde in Sicht',
 'El candidato novato',
 'The Call of the Silver Wibbler',
 'Frankie Best Hates Quests',
 'Trapped in the Overworld',
 'The Boy Who Biked the World: On the Road to Africa',
 'The 143-Storey Treehouse',
 'Unicorn Academy: Isla and Buttercup',
 "Herobrine's War",
 'Small Change for Stuart',
 'The Extreme',
 "Alain l'alien",
 'Wingfeather Tales',
 'Spider-Man gegen Sandman / Spider-Man und die Marvels',
 'Swamp Sting!',
 'Poison Jungle',
 '39 Clues: Cahills vs. Vespers',
 'Adventure Time - Too Many Bananas & Other Stories',
 'Blue Moon',
 "The Last Kids on Earth: June's Wild Flight",
 'Captain Underpants and the Terrifying Return of Tippy Tinkletrousers',
 'Mermaids of the Deep Blue Sea',
 'Flying Ninja!',
 'Fortress of the Stone Dragon',
 'Zoey and Sassafras: The Pod and the Bog',
 'PJ Masks - Héroes en Pijamas - ¡Los lobeznos!',
 'PJ Masks - Potència PJ!',
 'PJ Masks - Preparats per a l’acció!',
 'Mortel un jour, Mortel toujours!',
 'Pyjamasankarit - 3 minuutin iltasatuja',
 'PJ Masks - Vet aquí en Robot PJ!',
 'PJ Masks - PJ Robot',
 'Le géant de pierre',
 'Pyjamasankarit - Nousu taikavuorelle',
 'PJ Masks - Héroes en Pijamas - Catboy y el gran rescate de la torta de cumpleaños',
 'Tijl en de tijdbom',
 'Genius Camp',
 'The Talisman of Lostland',
 'Star Wars: The High Republic: A Test of Courage',
 'The Secret Explorers and the Plant Poachers',
 'The Red Slippers',
 'Captain Underpants and the Preposterous Plight of the Purple Potty People',
 "The Magician's Secret",
 'The Case of the Bizarre Bouquets',
 'Shockwave',
 'The Phantom of Nantucket',
 'The Swamp Robber',
 'The Magic Finger',
 'The Adventures of Captain Underpants',
 'Secret at Mystic Lake',
 'Fight for Dusty Divot',
 'I Survived the Sinking of the Titanic, 1912',
 'Showdown at Widow Creek',
 'Case of the Missing Marquess',
 'Nightshade',
 'Mystery of the Phantom Heist',
 "Mousse à l'école des pirates",
 'Riding Home Through Asia',
 'The Boy Who Biked the World: Riding the Americas',
 'El Misterio de la Montaña Azul',
 'Grand-mère Sucre et Grand-père Chocolat',
 'La chambre des pirates',
 'Tapator le dinosaure',
 'Une pomme pour deux',
 'Roméo et Biquette',
 'Bienvenue chez Vampirette',
 'Toc, toc ! Qui est là ?',
 'Un poisson nommé Marina',
 'Du lait pour mon chat',
 'Le grand voyage de Nils Holgersson',
 'Qui veut jouer avec Renard ?',
 'Le petit roi Moi Moi Moi !',
 'Pas de lunettes sur ma tête !',
 'Penny Berry y la batalla de Cairngorms',
 'Marvel - Tillbaka till urtiden',
 'Thor - Begynnelsen - Fin Fang Fooms uppgång och fall!',
 'Black Panther - Kampen om Wakanda',
 'Ali Baba and the Forty Thieves',
 'La fée Fifolette a cassé sa baguette',
 "Le gros chagrin d'Edgar",
 'Qui a volé le diamant de Big Jack ?',
 'La fée Fifolette déclenche des tempêtes',
 'Le petit chevalier courageux',
 'La banda della zuppa di piselli',
 'Princesse Sarah',
 "Le voleur d'Edith",
 'Veinte mil leguas de viaje submarino',
 'Historias de miedo',
 'Misterio en las vías',
 'Sofabanditen oder Die verrückte Befreiung der Hühner',
 'En el infierno',
 'PJ Masks: Carrera en la Montaña Misteriosa',
 'DC Jones and Adventure Command International 2',
 'Robatori a la platja',
 'Barbie - Dreamtopia',
 'Barbie - Els superpoders de princesa',
 'Barbie - Pop per a princeses',
 'Limamerirosvojen jäljillä',
 'Barbie - Buscant les gossetes',
 'Barbie - La porta secreta',
 'Die Hamsterdam-Verschwörung',
 'Els Barrufets - Històries dels barrufets',
 'La maison qui ne dormait jamais',
 'Els Barrufets - Històries de 3 minuts',
 'Wolvenhart',
 'Circus Maximus Rivals on the Track',
 'PJ Masks - Cursa cap a la Muntanya Misteriosa',
 "Super Pigiamini - Pronti all'azione!",
 'PJ Masks - En Gatnoi i el gran rescat del pastís d’aniversari',
 'Anatole Latuile fait son cinéma',
 'The Midnight Thief',
 'Suche nach der verborgenen Quelle',
 'El misterio del coleccionista de tazos',
 'Los Pitufos - Historias de Pitufos',
 'Dando la nota',
 'Los Pitufos - Historias de 3 minutos',
 'Vacaciones, no gracias',
 "A Baker's Guide to Robber Pie",
 'The Counterclockwise Heart',
 'Knight Sir Louis and the Dragon of Doooooom!',
 'Ferien auf Saltkrokan - Pelle findet einen Wunschstein',
 'Bob el Constructor - Perros y gatos',
 'The Secret of Haven Point',
 'The Mouse Watch in Space',
 'Freewater',
 'The Book of Stolen Time',
 'The Experiment',
 'The Exposed',
 'Big Sky Mountain: The Forest Wolves',
 "The Golem's Eye",
 'The Count of Monte Cristo',
 'Howl of the Wind Dragon',
 'Pony',
 'World Champions!',
 'Minecraft: Mob Squad',
 'The Threat',
 "The Tiger's Nest",
 'The Beekeeper Mystery',
 'The Shattered Castle',
 'Peanut Jones and the Illustrated City: from the creator of Draw with Rob',
 'Sparrow Rising',
 'Shadowghast',
 'The Beatryce Prophecy',
 'Brother Wulf',
 'Rise of the World Eater',
 'The Unadoptables',
 "Barbie - Equip d'espies",
 'The Mapmakers',
 'The Professor and the Puzzle',
 'The Paper Dolls',
 'The 39 Clues, Book 5',
 'Scorpia',
 'A Con Artist in Paris',
 'Tunnel of Bones',
 'The 13-Storey Treehouse',
 'The 39 Clues, Book 9',
 'Kid Normal and the Rogue Heroes',
 'Shine of the Silver Dragon',
 'Treasure of the Gold Dragon',
 'The Jungle Book',
 'The 1,000-Year-Old Boy',
 'Strangers on a Train',
 'Darkstalker',
 'Peter Rabbit 2',
 'Dinosaurs Before Dark',
 'The Outcast',
 'Wave of the Sea Dragon',
 'Escape from Aurora',
 'The Monkey King',
 'Getting Granny’s Glasses',
 'Where the Red Fern Grows',
 'The 39 Clues, Book 10',
 'Future of the Time Dragon',
 'Field Trip Fiasco',
 'Captain Underpants and the Big, Bad Battle of the Bionic Booger Boy, Part 2',
 'The Carpet People',
 'Clash at Fatal Fields',
 'Deception on the Set',
 'The Tale of Tom Kitten',
 '20.000 Leguas de viaje submarino [20,000 Leagues Under the Sea]',
 'Dungeons & Detectives',
 'A Script for Danger',
 'The Battle of Bayport',
 'Capitaine',
 'Iron Man - Rymdfantomernas invasion!',
 'City of Ghosts - Im Reich der vergessenen Geister',
 'Ariana y Arcana',
 'La aventura de Amunet',
 'Amigos de verdad',
 'Pan, nuestro hermano del bosque',
 'PJ Masks - Vet aquí els Mini Llops!',
 'Ufo in Seenot',
 'The Chromatics Camp at The Musical Mountain',
 'Attack of the Shadow-Crafters',
 'Не буду просить прощения',
 'Ritter Klapperschwert und die große Freundschaft',
 'H@Ck - Het instituut',
 'Маленький лорд Фаунтлерой',
 'Głupi Funio',
 'Un problema con alas',
 'Die Meckerpause',
 'El Club de la Luna Llena',
 'Spider-Man - En samling berättelser',
 'Enigma en el puente del naranjo',
 'Penny Berry y la cripta de los olvidados',
 'Penny Berry y la pócima mágica',
 'La casa embrujada',
 'Lady och Lufsen',
 'Тишина на задней парте!',
 'James und die fischige Fracht / Hiro und die widerspenstigen Waggons',
 'Avengers - God Jul!',
 'En busca del señor T',
 'Avengers - TRE spektakulära äventyr!',
 'Captain America och morgondagens armé!',
 'Superhjältarna',
 'Лесные истории',
 'Spider-Man - Kortslutning',
 'Перчатки Ариадны',
 'The Far-Finding Ring',
 'When the War Came Home',
 'Modig - Meridas önskan',
 'Il viaggio leggendario di Erick e Dominick',
 'Doctor Strange - Vejen til viden',
 'Pyjamasheltene - Kattedreng og den store fødselsdagskageredning',
 'Pyjamasheltene redder dagen!',
 'The Great Zombie Invasion',
 'The Buried Crown',
 'The Wishing Star & The North Pole Picnic',
 'Cora y los Corales',
 'Fortidens skygger',
 "Racconti dall'India",
 'Piratbarn har ikke længere brug for sin sut',
 'Alpaca My Bags',
 "L'île du mage",
 'Speedy',
 'The Santa List',
 'Paradise Pirates retten Captain Scratch',
 'Loca por Hugo',
 'Ninja Niller - Blodets Bånd: Del 4',
 'Marvel - Den stora sagosamlingen',
 'Bilar 3',
 'Falcon - Fäkta eller flyga',
 'Barbie - Aventura en el espacio',
 'El misterio de la virgulina inmortal',
 'Ein Mädchen namens Owl',
 'Antigua de Fortune of the High Seas',
 'The Smidgens',
 "Revolució a la botiga d'animals",
 'Te regalo el mundo',
 'Et regalo el món',
 'Revolución en la tienda de animales',
 'Ribblestrop Forever!',
 'Это грузовик, а это прицеп',
 'Страна Хороших Девочек',
 'Записки институтки',
 'Синичкин календарь',
 'Новые правила поведения для воспитанных детей',
 'Поллианна',
 'Психология окружающего мира. Дуня и кот Кисель на конюшне',
 'Тринадцатый подвиг Геракла. Рассказы о Чике (Сборник)',
 'Единорог для круглой принцессы',
 'Четыре желания',
 'Нектар для души. Вдохновляющие истории для детей 7-10 лет',
 'Ага, попался!',
 'Васюткино озеро. Рассказы для детей',
 'Das Feuer',
 'Familie Maulwurf auf der Flucht',
 'Die Spiegelspringer - Im Bann der Geschichten',
 'The Attack',
 'Symbiosis',
 'Stella und der Mondscheinvogel',
 'Saids Schicksale',
 'Surviving Jamestown',
 '¡Sálvese quien pueda!',
 'Cuentos locos para niños inteligentes',
 'Wednesday: The Forest of Secrets',
 'Ronan Boyle into the Strangeplace',
 'Girl Giant and the Jade War',
 'Kidnapped Colt',
 'Cómo como',
 'Der Zeitring',
 'Ivy & Bean Bound to Be Bad (Book 5)',
 'Ivy & Bean Take Care of the Babysitter (Book 4)',
 'Ivy & Bean Break the Fossil Record (Book 3)',
 'Moonrise',
 'Vega Jane and the End of Time',
 'The Suspicion',
 'The Pretender',
 'Hide and Geek',
 'Sunlight on the Snow Leopard',
 'Me and My Little Brain',
 'Coraline',
 'The Van Gogh Deception',
 'Moon Rising',
 'Abenteuer-Ferien bei Opa Balduin',
 'Hello Kitty - La aventura animal',
 'Hello Kitty - La estrella de televisión',
 'Hello Kitty - Vacaciones en la playa',
 'Hello Kitty - El misterio de la madalena',
 'Hello Kitty - La búsqueda del tesoro',
 'Hello Kitty - Sesión de belleza',
 'Ravenburcht',
 'De Utrolige 2',
 'Ariadna y la luna Lunera',
 "L'Ariadna i la lluna Pruna",
 'La Mariona i la Menjanits',
 'Captain Underpants and the Attack of the Talking Toilets',
 'Holes',
 'The 39 Clues, Book 1',
 'The Princess in Black, Books 1-3',
 'Pyjamasankarit - Tässä tulee Pyjamarobotti!',
 'Pyjamasankarit - Polkuvoimaa!',
 'PJ Masks - Sigues un heroi!',
 'Pyjamasankarit - Ollaan sankareita',
 'Pyjamasankarit - Tässä tulee susijengi',
 'Pyjamasankarit - Kolli ja synttärikakun pelastusoperaatio',
 'Fly High Crew: The Green Glow',
 'Vitello va a un cumpleaños de niñas',
 'Vitello compra un maravilloso regalo de Navidad',
 'Vitello salva el mundo',
 'Vitello construye un Abominable Hombre de las Nieves',
 'Vitello hace una obra de caridad',
 'Vitello pide un deseo',
 'Vitello pide un montón de chuches',
 'Barbie - En busca de las cachorritas',
 'El misterio del ladrón narizotas',
 'Willy y el arenque asesino',
 'Pasado por auga',
 'PJ Masks - ¡Los niños lobunos!',
 'Noémie Hollemechette',
 'Los Pitufos - Historias de Pitufos',
 'Los Pitufos - Historias de 3 minutos',
 'Il primo disastroso libro di Matt',
 'Françoise la mauvaise tête',
 'Sotto la stella del lupo',
 'Los Rescatadores Mágicos y la tostadora de los deseos',
 'Superhjältar på äventyr - Spider-Man får superhjälp!',
 'Atrapados en el monte Olimpo',
 'The Worst Class in the World Dares You!',
 'Der Ruf des Mondsteins',
 'Pizza Power',
 "The Case of the Smuggler's Curse",
 'The Lock-Eater',
 'Brave New Pond',
 'The Box-Car Children',
 'Wild River',
 'The Wild Robot: Booktrack Edition',
 'Skeleton Key',
 'Demon Dentist',
 'Hidden Pictures',
 'The Lost Continent',
 'Unicorn Academy: Ariana and Whisper',
 'A Long Walk to Water',
 'Talons of Power',
 'Bound for Danger',
 'Captain Underpants and the Big, Bad Battle of the Bionic Booger Boy, Part 1: The Night of the Nasty Nostril Nuggets',
 'Hello Kitty - El día de la boda',
 'Hello Kitty - La excursión escolar',
 'Hello Kitty - La princesa del pop',
 'Het\xa0oneindige\xa0verhaal',
 'Mariona y Comenoches',
 'Thomas@geraamte.net (Afrikaans Edition)',
 'Чучело',
 'Маленькая принцесса',
 'Маленький принц',
 'Warhammer Adventures: Battle for the Soulspring',
 'Warhammer Adventures: Fortress of Ghosts',
 'Black Powder',
 'Le Mystère du train de la nuit',
 'Drachenalarm',
 'Superjuffie!',
 'Begyndelsen - Storm i sigte',
 '101 Dalmatinere - Begyndelsen - Anitas hemmelige hvalp',
 'Złote rękawice Arachne!',
 'Die Traumwelt',
 'Swashbuckler',
 'Paddington, le roman du film',
 'Get a Hold of Your Elf!',
 'Niemals den roten Knopf drücken oder die Dinos drehen durch',
 'Le fabuloup gâteau de Gros-Louis',
 "Loup et ses amis. L'intégrale",
 "L'anniversaire de Louve",
 "Edmond le dragon et l'incendie",
 'La machine à vœux de Valentin',
 'La drôle de maladie de Demoiselle Yéti',
 'Le secret de Joshua',
 'Alfred et le monstre de la forêt',
 'Comenoches',
 'Mörtel und Maus wollen hoch hinaus',
 'Un viaje más allá de Sodor',
 'El prisionero de la fantasía',
 'Das Hotel der Wünsche',
 'Der Verrat',
 'Das verbotene Turnier',
 'Дениска на Севером полюсе [Deniska at the North Pole]',
 'Lampie',
 'Spider-Man rettet Weihnachten / Spider-Man und seine Insektenfreunde',
 'Otto der Flaschengeist',
 'Peter Pan',
 "L'Ogre qui aimait les champignons",
 'Une mission parfumée\xa0!',
 'De précieux passagers',
 'La Grande Course',
 'Un concert enflammé',
 'Thursdays with the Crown',
 'Marvel Spider-Man - 5-Min-Geschichten',
 'Un super match de football',
 'Un super chien de sauvetage',
 'The Spitfang Lizard',
 'Little Horror',
 'Un sauvetage magique',
 'Un cheval à sauver',
 'Canoë à la Dérive\xa0!',
 'Disparition au Zoo\xa0!',
 'Concours en péril',
 'La Tempête de Dhîves',
 'Im Bannkreis des Schwurs Teil 2',
 'Im Bannkreis des Schwurs Teil 1',
 'La Route du courage',
 'Bazar chez les locomotives',
 'Le Mystère de la montagne bleue',
 'Le Roi du chemin de fer',
 'Que le meilleur gagne !',
 'Los Atrevidos',
 'Lucía y Ema dan un paseo en bicicleta',
 'Lucía y Ema celebran sus cumpleaños',
 'Lucía recibe un cachorro de regalo',
 'Gulliver XXI',
 'Midnatt',
 'Den mörka floden',
 'Visionen',
 'Blood Captain',
 'Zeinumb. Parque de atracciones',
 'El mejor regalo del mundo',
 'The Hunt for the Five',
 'Un amico a sorpresa',
 'Eine dunkle Verschwörung',
 'Alarm im Park',
 'Los vestidos de Pancheta',
 'Aventures sur le continent',
 'Tafiti und der große Zauberer',
 'Silas and the Marvellous Misfits',
 'Cheeky and Charlemagne',
 'El Agujero Negro [The Black Hole]',
 'La Légende du trésor perdu de Chicalor',
 'Los rescatadores mágicos en las magiolimpiadas',
 'Los rescatadores mágicos en el bosque de los gamusinos',
 'El ladrón de la fantasía',
 'Freddy vs. School',
 'City of Rust',
 'Polly Pecorino',
 'Mambrú Perdió la Guerra [Mambrú Lost the War]',
 'Dragon Skin',
 'Eld och is',
 'Crowfall',
 'Die Muskeltiere und die große Käseverschwörung',
 'Tom und die Schildkrötenschmuggler',
 'Travesuritis aguda [Acute Travesuritis]',
 'Hola, ¿puedo ayudar?',

In [73]:
audible_dataset[audible_dataset['price']=='Free']

,name,author,narrator,time,releasedate,language,stars,price
983,Ringo & the Yogi,Writtenby:PrasunRoy,Narratedby:SiddhantaPinto,5 hrs and 18 mins,19-11-19,English,4 out of 5 stars4 ratings,Free
1414,The Velveteen Rabbit,Writtenby:MargeryWilliams,Narratedby:RichardArmitage,24 mins,14-08-20,English,4.5 out of 5 stars91 ratings,Free
1513,Billi Aur Moosarani [Cat and Musrani],Writtenby:Shivani,Narratedby:SarahHashmi,26 mins,14-10-21,Hindi,Not rated yet,Free
2932,Pariyon Ki Kahaniya [Fairy Tales],Writtenby:JacobGrimm,Narratedby:AnuradhaChauhan,2 hrs and 15 mins,08-12-21,Hindi,Not rated yet,Free
4547,101 Best Indian Fables for Children,Writtenby:StutiGupta,Narratedby:SunandhaRaghunathan,2 hrs and 26 mins,03-12-19,English,4 out of 5 stars3 ratings,Free
...,...,...,...,...,...,...,...,...
80021,FREE: The Undead,Writtenby:RRHaywood,Narratedby:DanMorgan,1 hr and 3 mins,24-02-15,English,4 out of 5 stars8 ratings,Free
81198,Supporters. Le Pilote,"Writtenby:PierreNiboyet,AudreyPoiret",Narratedby:BorisRehlinger,24 mins,29-10-20,french,Not rated yet,Free
82644,Boots Belts Berets,Writtenby:TanushreePodder,Narratedby:RannvijaySinghSingha,6 hrs and 59 mins,27-08-19,English,4.5 out of 5 stars158 ratings,Free
86771,Canada Is Awesome,Writtenby:NeilPasricha,Narratedby:NeilPasricha,34 mins,09-10-18,English,4.5 out of 5 stars29 ratings,Free
86927,Osez l'aventure avec Mike Horn. Le pilote,"Writtenby:MikeHorn,CharlesAudier","Narratedby:MikeHorn,CharlesAudier",24 mins,11-01-22,french,Not rated yet,Free

In [74]:
audible_dataset[audible_dataset['author']=='Writtenby:AndrewPeterson-editor,JonathanRogers,N.D.Wilson,']

,name,author,narrator,time,releasedate,language,stars,price
191,Wingfeather Tales,"Writtenby:AndrewPeterson-editor,JonathanRogers...",Narratedby:AndrewPeterson,10 hrs and 38 mins,23-03-21,English,Not rated yet,"1,382.00"

In [75]:
audible_dataset[
    ~audible_dataset['author'].str.contains(r'[A-Za-z]$', na=False)
]
#some entries in author end with differently like with , etc

,name,author,narrator,time,releasedate,language,stars,price
77,7 histoires d'aventures !,"Writtenby:BertrandFichou,NoraThullin,Catherine...","Narratedby:GuyChappelier,FrédéricSanchez,Marie...",43 mins,11-02-22,french,Not rated yet,679.00
191,Wingfeather Tales,"Writtenby:AndrewPeterson-editor,JonathanRogers...",Narratedby:AndrewPeterson,10 hrs and 38 mins,23-03-21,English,Not rated yet,"1,382.00"
241,Tapator le dinosaure,Writtenby:LessoeursBranchë,Narratedby:NatachaFabry,5 mins,09-02-22,french,Not rated yet,149.00
245,"Toc, toc ! Qui est là ?",Writtenby:LessoeursBranchë,Narratedby:OlivierClément,3 mins,09-02-22,french,Not rated yet,149.00
249,Qui veut jouer avec Renard ?,Writtenby:LessoeursBranchë,Narratedby:Jean-PaulBibé,3 mins,09-02-22,french,Not rated yet,149.00
...,...,...,...,...,...,...,...,...
87296,The Classic Continental Traveler's Companion (...,"Writtenby:CharlesDickens,WashingtonIrving,Mark...","Narratedby:ScottBrick,GabrielledeCuir,DonSchlo...",1 hr and 32 mins,19-08-04,English,Not rated yet,281.00
87334,Fernweh: Sprachurlaub in San Francisco,Writtenby:div.,Narratedby:N.N.,57 mins,20-04-10,german,Not rated yet,501.00
87363,Botswana,Writtenby:div.,Narratedby:DouglasWelbat,1 hr and 19 mins,19-05-17,german,Not rated yet,300.00
87401,Die Provence: Vom Mont Ventoux bis zur Côte Bleue,Writtenby:div.,"Narratedby:MarkusKästle,OlafPessler",2 hrs and 9 mins,12-12-17,german,Not rated yet,434.00
87406,Der anmuthsvolle Prater,Writtenby:div.,Narratedby:ElfriedeOtt,57 mins,20-07-10,german,Not rated yet,166.00

In [76]:
audible_dataset[
    audible_dataset['author'].str.endswith(',', na=False)
]

,name,author,narrator,time,releasedate,language,stars,price
77,7 histoires d'aventures !,"Writtenby:BertrandFichou,NoraThullin,Catherine...","Narratedby:GuyChappelier,FrédéricSanchez,Marie...",43 mins,11-02-22,french,Not rated yet,679.00
191,Wingfeather Tales,"Writtenby:AndrewPeterson-editor,JonathanRogers...",Narratedby:AndrewPeterson,10 hrs and 38 mins,23-03-21,English,Not rated yet,"1,382.00"
387,Тишина на задней парте!,"Writtenby:АлександрЦыпкин,АллаЛихачёва,Алексан...","Narratedby:ЕленаДельвер,ИгорьСергеев,МаксимСер...",3 hrs and 5 mins,23-12-21,russian,Not rated yet,200.00
751,Bamse ja noita-akan tytär,"Writtenby:SofieForsman,IdaKjellin,CharlottaBor...",Narratedby:Ville-VeikkoNiemelä,27 mins,04-03-22,finnish,Not rated yet,32.00
771,Getting to the Bottom of Global Warming,"Writtenby:TerryCollins,BillAnderson,TodSmith,",Narratedby:anonymous,15 mins,25-02-22,English,Not rated yet,93.00
...,...,...,...,...,...,...,...,...
86941,Wieder fliegen lernen,"Writtenby:SamanthaBloom,CameronBloom,BradleyTr...",Narratedby:SandraSchwittau,3 hrs and 18 mins,25-10-21,german,Not rated yet,468.00
87286,Rome Antique,"Writtenby:PaoloCarafa,GiovanniRicci,MariaGrazi...",Narratedby:ZavierSartre,30 mins,02-10-17,french,Not rated yet,190.00
87288,Rzym starozytny,"Writtenby:PaoloCarafa,GiovanniRicci,MariaGrazi...",Narratedby:ZbigniewDziduch,28 mins,02-10-17,polish,Not rated yet,190.00
87290,Starozytny Egipt,"Writtenby:MariaPiaCesaretti,SilviaEinaudi,Mari...",Narratedby:ZbigniewDziduch,45 mins,29-09-17,polish,Not rated yet,228.00
87296,The Classic Continental Traveler's Companion (...,"Writtenby:CharlesDickens,WashingtonIrving,Mark...","Narratedby:ScottBrick,GabrielledeCuir,DonSchlo...",1 hr and 32 mins,19-08-04,English,Not rated yet,281.00

In [77]:
audible_dataset[
    ~audible_dataset['name'].str.contains(r'[A-Za-z]$', na=False)
]

,name,author,narrator,time,releasedate,language,stars,price
0,Geronimo Stilton #11 & #12,Writtenby:GeronimoStilton,Narratedby:BillLobely,2 hrs and 20 mins,04-08-08,English,5 out of 5 stars34 ratings,468.00
4,"The Lightning Thief: Percy Jackson, Book 1",Writtenby:RickRiordan,Narratedby:JesseBernstein,10 hrs,13-01-10,English,4.5 out of 5 stars181 ratings,820.00
10,"The Titan's Curse: Percy Jackson, Book 3",Writtenby:RickRiordan,Narratedby:JesseBernstein,8 hrs and 48 mins,14-01-10,English,4.5 out of 5 stars130 ratings,820.00
11,Magic Tree House Collection: Books 9-16,Writtenby:MaryPopeOsborne,Narratedby:MaryPopeOsborne,5 hrs and 23 mins,24-08-11,English,5 out of 5 stars6 ratings,"1,206.00"
12,Magic Tree House Collection: Books 1-8,Writtenby:MaryPopeOsborne,Narratedby:MaryPopeOsborne,6 hrs and 1 min,27-09-11,English,5 out of 5 stars7 ratings,"1,206.00"
...,...,...,...,...,...,...,...,...
87383,"Mit 90 auf dem Jakobsweg: Wenn nicht jetzt, wa...",Writtenby:MargarethaToppelreiter,"Narratedby:KarinToppelreiter,MichaelToppelreit...",3 hrs and 7 mins,13-12-16,german,Not rated yet,267.00
87393,Longe do mar [Far from the Sea],Writtenby:PauloMoura,Narratedby:AxelAxel,3 hrs and 19 mins,09-04-18,portuguese,Not rated yet,537.00
87404,Laufen. Essen. Schlafen.,Writtenby:ChristineThürmer,Narratedby:BarbaraStoll,8 hrs and 23 mins,08-11-16,german,Not rated yet,468.00
87420,Wo geht's denn hier zum Glück?,Writtenby:MaikevandenBoom,Narratedby:SharyReeves,4 hrs and 44 mins,27-04-15,german,Not rated yet,468.00
87433,Spaziergang nach Syrakus im Jahre 1802,Writtenby:JohannGottfriedSeume,Narratedby:ThomasThieme,7 hrs and 9 mins,19-03-15,german,Not rated yet,233.00

In [78]:
audible_dataset[
    ~audible_dataset['narrator'].str.contains(r'[A-Za-z]$', na=False)
]

,name,author,narrator,time,releasedate,language,stars,price
70,El fantasma de la bodega,Writtenby:FranciscoDíazValladares,Narratedby:NuriaSamsó,2 hrs and 23 mins,04-04-22,spanish,Not rated yet,192.00
77,7 histoires d'aventures !,"Writtenby:BertrandFichou,NoraThullin,Catherine...","Narratedby:GuyChappelier,FrédéricSanchez,Marie...",43 mins,11-02-22,french,Not rated yet,679.00
94,Welcome to Smellville,Writtenby:R.L.Stine,"Narratedby:JordanFisher,DaschaPolanco,JonieceA...",3 hrs and 18 mins,29-09-20,English,Not rated yet,585.00
96,The Midnight Gang,Writtenby:DavidWalliams,"Narratedby:DavidWalliams,PeterSerafinowicz,Mor...",6 hrs and 9 mins,15-11-16,English,4.5 out of 5 stars3 ratings,322.00
106,Once Upon a Crime,Writtenby:RobinStevens,"Narratedby:KatieLeung,RebeccaLee,AlexanderCapon,",6 hrs and 50 mins,05-08-21,English,Not rated yet,615.00
...,...,...,...,...,...,...,...,...
87384,Weltkulturerbe - Trier,Writtenby:TatjanaWagner,"Narratedby:FrankArnold,NicoleBoguth,ChristineD...",56 mins,04-06-09,german,Not rated yet,233.00
87389,Fischland Darss,"Writtenby:HeinrichHeine,JosephRoth,HansFallada",Narratedby:GunterSchoß,53 mins,05-05-11,german,Not rated yet,334.00
87415,Spaziergang durch Lissabon,Writtenby:SaschaLübbe,"Narratedby:HarryKühn,UlrikeHübschmann,Gabriele...",1 hr and 19 mins,06-03-14,german,Not rated yet,233.00
87424,Kapellenweg Leukerbad,Writtenby:Jean-MariePerrig,Narratedby:N.N.,47 mins,28-05-10,german,Not rated yet,334.00
87435,Weltkulturerbe - Schwetzingen,Writtenby:ThomasRothkegel,"Narratedby:AndreaHörnke-Trieß,ChristianWeiß",57 mins,04-06-09,german,Not rated yet,233.00

In [ ]:
audible_dataset[
    ~audible_dataset['time'].str.match(
        r'^(\d+\s(?:hrs|hr)(?:\sand\s\d+\s(mins|min))?|\d+\s(mins|min))$',
        na=False
    )
]

#^(\d+\s(?:hrs|hr)-->this one basically says startwith digits(one or more) then space then choose one of hrs or hr 
#(?:\sand\s\d+\s(?:mins|min))?-->notice this group is optional we might have 1 hr only or 2 hrs only 
#\d+\s(?:mins|min)-->this one allows for only minutes like 5 minutes or 1 min

,name,author,narrator,time,releasedate,language,stars,price
1401,The Story of Ice Cream,Writtenby:StacyTaus-Bolstad,Narratedby:BookBuddyDigitalMedia,Less than 1 minute,01-01-21,English,Not rated yet,164.00
1403,The Story of Salt,Writtenby:LisaOwings,Narratedby:BookBuddyDigitalMedia,Less than 1 minute,01-01-21,English,Not rated yet,164.00
1404,The Story of Milk,Writtenby:StacyTaus-Bolstad,Narratedby:BookBuddyDigitalMedia,Less than 1 minute,01-01-21,English,Not rated yet,164.00
1408,The Story of an Apple,Writtenby:StacyTaus-Bolstad,Narratedby:BookBuddyDigitalMedia,Less than 1 minute,01-01-21,English,Not rated yet,164.00
1409,We Like the Summer,Writtenby:KatiePeters,Narratedby:BookBuddyDigitalMedia,Less than 1 minute,01-01-21,English,Not rated yet,164.00
...,...,...,...,...,...,...,...,...
87171,第二十五話サン・ミシェルのいいカフェ：ぼくの旅の手帖〜または珈琲のある風景,Writtenby:森本哲郎,Narratedby:小野田英一,Less than 1 minute,20-11-15,japanese,Not rated yet,139.00
87175,第九話オラン最後の夕べ：ぼくの旅の手帖〜または珈琲のある風景,Writtenby:森本哲郎,Narratedby:小野田英一,Less than 1 minute,19-11-15,japanese,Not rated yet,139.00
87176,第一話リューベックの追憶:ぼくの旅の手帖〜または珈琲のある風景,Writtenby:森本哲郎,Narratedby:小野田英一,Less than 1 minute,23-07-15,japanese,Not rated yet,139.00
87180,第七話バグダードの茶屋:ぼくの旅の手帖〜または珈琲のある風景,Writtenby:森本哲郎,Narratedby:小野田英一,Less than 1 minute,13-07-15,japanese,Not rated yet,139.00
87192,第十八話バンコックの憂鬱：ぼくの旅の手帖〜または珈琲のある風景,Writtenby:森本哲郎,Narratedby:小野田英一,Less than 1 minute,19-11-15,japanese,Not rated yet,139.00

In [ ]:
audible_dataset[
    audible_dataset['author'].str.contains(r'-[A-Za-z]+', na=False)
]
#some entries in author contain words like illustrator editor traductor etc

,name,author,narrator,time,releasedate,language,stars,price
74,Barnabas der Wolkenschaufler,"Writtenby:SophieSchoenwald,NadineReitz-Illustr...",Narratedby:BerndReheuser,2 hrs and 56 mins,04-04-22,german,Not rated yet,200.00
109,Danger at Dead Man's Pass,"Writtenby:M.G.Leonard,SamSedgman,ElisaPaganell...",Narratedby:JotDavies,6 hrs and 48 mins,16-09-21,English,Not rated yet,323.00
117,Barbie - Aventura espacial,"Writtenby:Mattel,MartaCisaMuñoz-traductor",Narratedby:MiriamMonlleo,12 mins,02-02-22,catalan,Not rated yet,76.00
131,Three Lost Seeds,"Writtenby:StephieMorton,NicoleWong-illustrator",Narratedby:StevenJayCohen,13 mins,08-02-22,English,Not rated yet,234.00
142,The Christmasaurus and the Naughty List,"Writtenby:TomFletcher,ShaneDevries-illustrator","Narratedby:PaulShelley,TomFletcher",6 hrs and 15 mins,14-10-21,English,Not rated yet,615.00
...,...,...,...,...,...,...,...,...
87407,Tour de San Francisco,Writtenby:HermineStampa-Rabe,Narratedby:HermineStampa-Rabe,4 hrs and 15 mins,10-04-15,german,Not rated yet,434.00
87412,Die City-West am Kurfürstendamm,"Writtenby:PatrickGschwind,Wolf-RüdigerWilhelm",Narratedby:KarenSchulz-Vobach,1 hr and 16 mins,06-06-11,german,Not rated yet,133.00
87414,Rund um den Savignyplatz,"Writtenby:PatrickGschwind,Wolf-RüdigerWilhelm",Narratedby:KarenSchulz-Vobach,1 hr and 12 mins,06-06-11,german,Not rated yet,133.00
87416,"Unter den Linden, the old centre of Berlin","Writtenby:PatrickGschwind,Wolf-RüdigerWilhelm",Narratedby:PeterFarkas,1 hr and 57 mins,06-06-11,English,Not rated yet,133.00
87424,Kapellenweg Leukerbad,Writtenby:Jean-MariePerrig,Narratedby:N.N.,47 mins,28-05-10,german,Not rated yet,334.00

In [97]:
audible_dataset[
    audible_dataset['narrator'].str.contains(r'-[A-Za-z]+', na=False)
]

,name,author,narrator,time,releasedate,language,stars,price
94,Welcome to Smellville,Writtenby:R.L.Stine,"Narratedby:JordanFisher,DaschaPolanco,JonieceA...",3 hrs and 18 mins,29-09-20,English,Not rated yet,585.00
235,Mousse à l'école des pirates,Writtenby:EliseRengot,Narratedby:Jean-PaulBibé,6 mins,15-02-22,french,Not rated yet,151.00
249,Qui veut jouer avec Renard ?,Writtenby:LessoeursBranchë,Narratedby:Jean-PaulBibé,3 mins,09-02-22,french,Not rated yet,149.00
276,Limamerirosvojen jäljillä,Writtenby:VeeraVähämaa,Narratedby:Ari-MattiHedman,2 hrs and 14 mins,27-01-22,finnish,Not rated yet,166.00
290,Suche nach der verborgenen Quelle,"Writtenby:ChenJiatong,UlrikeKöbele-Übersetzer",Narratedby:Michael-CheKoch,6 hrs and 45 mins,09-02-22,german,Not rated yet,367.00
...,...,...,...,...,...,...,...,...
87407,Tour de San Francisco,Writtenby:HermineStampa-Rabe,Narratedby:HermineStampa-Rabe,4 hrs and 15 mins,10-04-15,german,Not rated yet,434.00
87412,Die City-West am Kurfürstendamm,"Writtenby:PatrickGschwind,Wolf-RüdigerWilhelm",Narratedby:KarenSchulz-Vobach,1 hr and 16 mins,06-06-11,german,Not rated yet,133.00
87414,Rund um den Savignyplatz,"Writtenby:PatrickGschwind,Wolf-RüdigerWilhelm",Narratedby:KarenSchulz-Vobach,1 hr and 12 mins,06-06-11,german,Not rated yet,133.00
87434,Weltkulturerbe - Der Limes,Writtenby:ReinoldHermanns,"Narratedby:AndreaHoernke-Trieß,PeterBinder",56 mins,04-06-09,german,Not rated yet,233.00
87435,Weltkulturerbe - Schwetzingen,Writtenby:ThomasRothkegel,"Narratedby:AndreaHörnke-Trieß,ChristianWeiß",57 mins,04-06-09,german,Not rated yet,233.00